services:
  database:
    container_name: db_backend
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    image: 'postgres:latest'
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgresql-data:
    driver: local
    name: postgresql-data