services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf     
      - upload-files:/srv/upload
    depends_on:
      app:
        condition: service_started 
  celery_worker:
    container_name: celery_worker
    volumes:
      - upload-files:/srv/upload
    build: './backend'
    restart: on-failure
    command: celery -A make_celery  worker --loglevel INFO
    env_file:
      - .env
  app:
    container_name: backend_ifpv
    command: gunicorn --workers=4  app:app  --bind 0.0.0.0:8000
    volumes:
      - upload-files:/srv/upload
    build: './backend'
    restart: on-failure
    env_file:
      - .env
volumes:
  upload-files:
    driver: local
    name: upload-files