services:
  app:
    platform: linux/amd64
    container_name: backend_ifpv
    command: gunicorn --workers=4  app:app --bind 0.0.0.0:8000 --worker-connections=20
    build: './backend'
    restart: on-failure
    env_file:
      - .env
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf     
    depends_on:
      - app