version: "3.7"
services:
  app:
    container_name: backend_ifpv
    build: './backend'
    command: gunicorn --workers=4  app:app  --bind 0.0.0.0:8080
    restart: on-failure
    ports:
      - 8080:8080
    env_file:
      - .env